version: '3.9'

services:

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=aerospace_inspection
      - SECRET_KEY=supersecretkey123
      - DEBUG=True
      - YOLO_SERVICE_URL=http://localhost:8001
      - AGENT_SERVICE_URL=http://localhost:8002
      - PDF_SERVICE_URL=http://localhost:8003
    volumes:
      - pdf_storage:/app/artifacts/reports
      - uploads:/app/data/uploads
      - chroma_data:/app/data/vectorstore
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=aerospace_inspection
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped

  chroma:
    image: chromadb/chroma
    ports:
      - "8004:8000"
    volumes:
      - chroma_data:/chroma/chroma
    restart: unless-stopped

volumes:
  postgres_data:
  pdf_storage:
  uploads:
  ollama_models:
  chroma_data: