class InspectionType:
    GVI = "GVI"
    DVI = "DVI"
    SDI = "SDI"
    ALL = [GVI, DVI, SDI]

class InspectionStatus:
    CREATED = "CREATED"
    DETECTING = "DETECTING"
    DETECTION_COMPLETE = "DETECTION_COMPLETE"
    INVESTIGATING = "INVESTIGATING"
    AGENT_COMPLETE = "AGENT_COMPLETE"
    AIRWORTHINESS_APPROVED = "AIRWORTHINESS_APPROVED"
    FLAGGED_FOR_REVISION = "FLAGGED_FOR_REVISION"
    FINDINGS_APPROVED = "FINDINGS_APPROVED"
    GENERATING = "GENERATING"
    COMPLETE = "COMPLETE"
    ALL = [
        CREATED, DETECTING, DETECTION_COMPLETE,
        INVESTIGATING, AGENT_COMPLETE,
        AIRWORTHINESS_APPROVED, FLAGGED_FOR_REVISION,
        FINDINGS_APPROVED, GENERATING, COMPLETE
    ]