class InspectionStatus:
    CREATED = "CREATED"
    DETECTING = "DETECTING"
    DETECTION_COMPLETE = "DETECTION_COMPLETE"
    INVESTIGATING = "INVESTIGATING"
    AGENT_COMPLETE = "AGENT_COMPLETE"
    FINDINGS_APPROVED = "FINDINGS_APPROVED"
    GENERATING = "GENERATING"
    COMPLETE = "COMPLETE"
    ALL = [CREATED, DETECTING, DETECTION_COMPLETE, INVESTIGATING, AGENT_COMPLETE, FINDINGS_APPROVED, GENERATING, COMPLETE]