"""add zone_id and inspection_type to inspections

Revision ID: a6e70c459810
Revises: c324f3c33131
Create Date: 2026-07-03 16:49:38.046082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e70c459810'
down_revision: Union[str, Sequence[str], None] = 'c324f3c33131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('zone_id', sa.String(), nullable=True))
    op.add_column('inspections', sa.Column('inspection_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'inspection_type')
    op.drop_column('inspections', 'zone_id')
    # ### end Alembic commands ###
