"""create all tables

Revision ID: c324f3c33131
Revises: 
Create Date: 2026-06-26 12:54:26.957301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c324f3c33131'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('aircraft_type', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('agent_findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('inspection_id', sa.String(), nullable=False),
    sa.Column('probable_causes', sa.JSON(), nullable=True),
    sa.Column('regulation_refs', sa.JSON(), nullable=True),
    sa.Column('airworthiness_status', sa.String(), nullable=True),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('repair_steps', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defect_findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('inspection_id', sa.String(), nullable=False),
    sa.Column('defect_type', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('bbox_x', sa.Integer(), nullable=True),
    sa.Column('bbox_y', sa.Integer(), nullable=True),
    sa.Column('bbox_w', sa.Integer(), nullable=True),
    sa.Column('bbox_h', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('inspection_id', sa.String(), nullable=False),
    sa.Column('defect_report_path', sa.String(), nullable=True),
    sa.Column('work_order_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('zone_name', sa.String(), nullable=False),
    sa.Column('zone_label', sa.String(), nullable=False),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('last_inspection_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['last_inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zones')
    op.drop_table('reports')
    op.drop_table('defect_findings')
    op.drop_table('agent_findings')
    op.drop_table('users')
    op.drop_table('inspections')
    # ### end Alembic commands ###
