/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './web_utils/routes/__root'
import { Route as LoginRouteImport } from './web_utils/routes/login'
import { Route as AppRouteImport } from './web_utils/routes/_app'
import { Route as IndexRouteImport } from './web_utils/routes/index'
import { Route as AppTwinRouteImport } from './web_utils/routes/_app.twin'
import { Route as AppReportsRouteImport } from './web_utils/routes/_app.reports'
import { Route as AppInspectionRouteImport } from './web_utils/routes/_app.inspection'
import { Route as AppAnalysisRouteImport } from './web_utils/routes/_app.analysis'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTwinRoute = AppTwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionRoute = AppInspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalysisRoute = AppAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analysis': typeof AppAnalysisRoute
  '/inspection': typeof AppInspectionRoute
  '/reports': typeof AppReportsRoute
  '/twin': typeof AppTwinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analysis': typeof AppAnalysisRoute
  '/inspection': typeof AppInspectionRoute
  '/reports': typeof AppReportsRoute
  '/twin': typeof AppTwinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analysis': typeof AppAnalysisRoute
  '/_app/inspection': typeof AppInspectionRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/twin': typeof AppTwinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/analysis' | '/inspection' | '/reports' | '/twin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/analysis' | '/inspection' | '/reports' | '/twin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/analysis'
    | '/_app/inspection'
    | '/_app/reports'
    | '/_app/twin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/twin': {
      id: '/_app/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof AppTwinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspection': {
      id: '/_app/inspection'
      path: '/inspection'
      fullPath: '/inspection'
      preLoaderRoute: typeof AppInspectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analysis': {
      id: '/_app/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AppAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalysisRoute: typeof AppAnalysisRoute
  AppInspectionRoute: typeof AppInspectionRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTwinRoute: typeof AppTwinRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalysisRoute: AppAnalysisRoute,
  AppInspectionRoute: AppInspectionRoute,
  AppReportsRoute: AppReportsRoute,
  AppTwinRoute: AppTwinRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
